#!/usr/bin/env bash

# You'll either need to uncomment and fill out the variables below
# or have them filled out in an ~/.env file like I do.

#HALLWAY_MEMBERS=   #location of hallway_members file
#HALLWAY_DIRECTORY= #directory that your twtxt file lives
#HALLWAY_DIRECTORY= #name of your twtxt file

. ~/.env

command -v jq >/dev/null 2>&1 ||
  { echo >&2 "jq is required for this script to work correctly, but not found. Aborting."; exit 1; }

show_authors()
{
  if [ ! -f $HALLWAY_MEMBERS ]; then
    echo "Hallway members file doesn't exist. Run hallway sync to create one."
    exit 1
  fi
  grep @ $HALLWAY_MEMBERS
}

show_feed_urls()
{
  if [ ! -f $HALLWAY_MEMBERS ]; then
    echo "Hallway members file doesn't exist. Run hallway sync to create one."
    exit 1
  fi
  grep -v @ $HALLWAY_MEMBERS
}

show_feeds()
{
  curl -s https://webring-checker.now.sh/hallway?format=simplified | jq "reverse | .[] | {author, body}"
}

sync_names()
{
  if [ ! -f $HALLWAY_MEMBERS ]; then
    echo "Creating hallway members file"
  fi
  curl -s https://webring-checker.now.sh/sites | jq -r ".[] | select(.feed) | (\"@\" + .author, .feed)" > $HALLWAY_MEMBERS
}

write_on_wall()
{
  DATE=$(date -u -Iseconds)
  HALLWAY_LOCATION=$HALLWAY_DIRECTORY$HALLWAY_FILE

  if [ ! -f $HALLWAY_LOCATION ]; then
    echo "$HALLWAY_LOCATION doesn't exist yet. Would you like to create it? (y/n)"
    read CREATION
    if [ $CREATION = 'y']; then
      touch $HALLWAY_LOCATION && echo "created file $HALLWAY_FILE"
    else
      echo 'Ok, bye.'
      exit 1
    fi
  fi

  AUTHOR=$(grep -o '@\w*' <<< $@)

  if [ $AUTHOR ]; then
    echo $AUTHOR
    FEED=$(grep -A1 $AUTHOR $HALLWAY_MEMBERS)
    MSG=${@/$AUTHOR/@<${FEED:1}>;}
  else
    MSG=$@
  fi

  echo -e $DATE'\t'$MSG | cat - $HALLWAY_LOCATION > /tmp/out && mv /tmp/out $HALLWAY_LOCATION

  echo "Would you like to deploy this? (y/n)"
  read response

  # Replace the below wiht your custom deployment script
  if [ $response = 'y' ]; then
    cd $HALLWAY_DIRECTORY
    git add .
    git commit -m "Shouting in the hallway"
    git push origin master
  fi
}

usage()
{
  echo "Usage: hallway [command]
    -h, --help      List commands
    authors   View all available authors in the hallway
    channels  View all used available channels
    feeds     View a listing of all feed urls
    gander    Take a gander at the hallway
    sync      Syncs list of members in the hallway
    tags      List all used tags
    write     Write new message for the hallway"
}

case $1 in
  authors)
    show_authors
    ;;
  channels)
    echo "Channels not implimented yet"
    ;;
  feeds)
    show_feed_urls
    ;;
  gander)
    show_feeds
    ;;
  -h|--help)
    usage
    ;;
  sync)
    sync_names
    ;;
  tags)
    echo "Tags not implimented yet"
    ;;
  write)
    write_on_wall $2
    ;;
  *)
    usage
esac

